import { 
  ImageDown, Maximize, Crop, RotateCw, FileDown, 
  FileText, Layers, Scissors, FileImage, 
  Video, Music, Wand2, QrCode, Sparkles, Image, FileVideo, Barcode, Palette, Code,
  LucideIcon, Unlock, Lock, Type, RefreshCw
} from "lucide-react";

export interface ToolDefinition {
  id: string;
  title: string;
  description: string;
  category: "Image" | "PDF" | "Video" | "Audio" | "AI" | "Utilities";
  keywords: string[];
  href: string;
  icon: LucideIcon;
  color: string;
  status: "active" | "coming-soon";
  featured: boolean;
  popular: boolean;
  relatedToolIds?: string[];
  isSubTool?: boolean;
}

export const TOOLS: ToolDefinition[] = [
  // IMAGE TOOLS
  // Sub-tools for Image Conversions
  {
    id: "jpg-to-png",
    title: "JPG to PNG",
    description: "Convert JPG images to PNG format with transparency.",
    category: "Image",
    keywords: ["jpg to png", "convert", "image"],
    href: "/jpg-to-png",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: true,
    isSubTool: true,
    relatedToolIds: ["convert-image", "png-to-jpg"],
  },
  {
    id: "png-to-jpg",
    title: "PNG to JPG",
    description: "Convert PNG images to JPG format.",
    category: "Image",
    keywords: ["png to jpg", "convert", "image"],
    href: "/png-to-jpg",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: true,
    isSubTool: true,
    relatedToolIds: ["convert-image", "jpg-to-png"],
  },
  {
    id: "webp-to-png",
    title: "WEBP to PNG",
    description: "Convert WEBP images to PNG format.",
    category: "Image",
    keywords: ["webp to png", "convert", "image"],
    href: "/webp-to-png",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: false,
    isSubTool: true,
    relatedToolIds: ["convert-image"],
  },
  {
    id: "png-to-webp",
    title: "PNG to WEBP",
    description: "Convert PNG images to WEBP format.",
    category: "Image",
    keywords: ["png to webp", "convert", "image"],
    href: "/png-to-webp",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: false,
    isSubTool: true,
    relatedToolIds: ["convert-image"],
  },
  {
    id: "jpg-to-webp",
    title: "JPG to WEBP",
    description: "Convert JPG images to WEBP format.",
    category: "Image",
    keywords: ["jpg to webp", "convert", "image"],
    href: "/jpg-to-webp",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: false,
    isSubTool: true,
    relatedToolIds: ["convert-image"],
  },
  {
    id: "webp-to-jpg",
    title: "WEBP to JPG",
    description: "Convert WEBP images to JPG format.",
    category: "Image",
    keywords: ["webp to jpg", "convert", "image"],
    href: "/webp-to-jpg",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: false,
    isSubTool: true,
    relatedToolIds: ["convert-image"],
  },
  {
    id: "avif-to-jpg",
    title: "AVIF to JPG",
    description: "Convert AVIF images to JPG format.",
    category: "Image",
    keywords: ["avif to jpg", "convert", "image"],
    href: "/avif-to-jpg",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: false,
    isSubTool: true,
    relatedToolIds: ["convert-image"],
  },
  {
    id: "jpg-to-avif",
    title: "JPG to AVIF",
    description: "Convert JPG images to AVIF format.",
    category: "Image",
    keywords: ["jpg to avif", "convert", "image"],
    href: "/jpg-to-avif",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: false,
    isSubTool: true,
    relatedToolIds: ["convert-image"],
  },
  {
    id: "bmp-to-png",
    title: "BMP to PNG",
    description: "Convert BMP images to PNG format.",
    category: "Image",
    keywords: ["bmp to png", "convert", "image"],
    href: "/bmp-to-png",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: false,
    isSubTool: true,
    relatedToolIds: ["convert-image"],
  },
  {
    id: "gif-to-png",
    title: "GIF to PNG",
    description: "Convert GIF images to PNG format.",
    category: "Image",
    keywords: ["gif to png", "convert", "image"],
    href: "/gif-to-png",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: false,
    isSubTool: true,
    relatedToolIds: ["convert-image"],
  },
  {
    id: "compress-image",
    title: "Compress Image",
    description: "Reduce image size without losing quality.",
    category: "Image",
    relatedToolIds: ["rotate-image","avif-to-jpg","webp-to-png","crop-image"],
    keywords: ["compress", "image", "reduce", "size", "tiny", "jpg", "png", "webp", "optimize"],
    href: "/compress-image",
    icon: ImageDown,
    color: "text-green-600",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "resize-image",
    title: "Resize Image",
    description: "Change image dimensions instantly.",
    category: "Image",
    relatedToolIds: ["avif-to-jpg","jpg-to-webp","webp-to-png","compress-image"],
    keywords: ["resize", "image", "dimensions", "scale", "width", "height", "pixel", "resolution"],
    href: "/resize-image",
    icon: Maximize,
    color: "text-blue-600",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "crop-image",
    title: "Crop Image",
    description: "Crop photos to exact ratios or custom sizes.",
    category: "Image",
    relatedToolIds: ["jpg-to-png","bmp-to-png","avif-to-jpg","webp-to-png"],
    keywords: ["crop", "image", "cut", "trim", "ratio", "square", "aspect"],
    href: "/crop-image",
    icon: Crop,
    color: "text-purple-600",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "rotate-image",
    title: "Rotate Image",
    description: "Rotate or flip images easily.",
    category: "Image",
    relatedToolIds: ["jpg-to-webp","jpg-to-avif","jpg-to-png","compress-image"],
    keywords: ["rotate", "image", "flip", "turn", "degree", "angle", "upside down"],
    href: "/rotate-image",
    icon: RotateCw,
    color: "text-amber-600",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "convert-image",
    title: "Convert Image",
    description: "Convert between JPG, PNG, WEBP and AVIF.",
    category: "Image",
    relatedToolIds: ["gif-to-png","bmp-to-png","resize-image","rotate-image"],
    keywords: ["convert", "image", "format", "change", "jpg", "png", "webp", "avif", "gif"],
    href: "/convert-image",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: true,
    popular: true,
  },

  // PDF TOOLS
  {
    id: "compress-pdf",
    title: "Compress PDF",
    description: "Reduce PDF file size for easy sharing.",
    category: "PDF",
    relatedToolIds: ["pdf-to-excel","ppt-to-pdf","excel-to-pdf","rotate-pdf"],
    keywords: ["compress", "pdf", "reduce", "size", "document", "optimize"],
    href: "/compress-pdf",
    icon: FileText,
    color: "text-red-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "merge-pdf",
    title: "Merge PDF",
    description: "Combine multiple PDFs into one.",
    category: "PDF",
    relatedToolIds: ["split-pdf","rotate-pdf","pdf-to-word","protect-pdf"],
    keywords: ["merge", "pdf", "combine", "join", "together", "document"],
    href: "/merge-pdf",
    icon: Layers,
    color: "text-orange-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "split-pdf",
    title: "Split PDF",
    description: "Extract specific pages from a PDF.",
    category: "PDF",
    relatedToolIds: ["pdf-to-word","pdf-to-ppt","pdf-to-excel","word-to-pdf"],
    keywords: ["split", "pdf", "extract", "separate", "pages", "divide"],
    href: "/split-pdf",
    icon: Scissors,
    color: "text-amber-500",
    status: "active",
    featured: false,
    popular: true,
  },
  {
    id: "unlock-pdf",
    title: "Unlock PDF",
    description: "Remove password protection from PDF.",
    category: "PDF",
    relatedToolIds: ["compress-pdf","pdf-to-image","organize-pdf","merge-pdf"],
    keywords: ["unlock", "pdf", "password", "decrypt", "remove", "protection", "security"],
    href: "/unlock-pdf",
    icon: Unlock,
    color: "text-green-500",
    status: "active",
    featured: false,
    popular: true,
  },
  {
    id: "protect-pdf",
    title: "Protect PDF",
    description: "Encrypt your PDF files with a password.",
    category: "PDF",
    relatedToolIds: ["excel-to-pdf","delete-pages","pdf-to-excel","pdf-to-image"],
    keywords: ["protect", "pdf", "password", "encrypt", "secure", "permissions", "lock"],
    href: "/protect-pdf",
    icon: Lock,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: true,
  },
  {
    id: "rotate-pdf",
    title: "Rotate PDF",
    description: "Rotate PDF pages easily and permanently.",
    category: "PDF",
    relatedToolIds: ["pdf-to-excel","pdf-to-ppt","ppt-to-pdf","watermark-pdf"],
    keywords: ["rotate", "pdf", "turn", "pages", "degree", "orientation"],
    href: "/rotate-pdf",
    icon: RotateCw,
    color: "text-amber-500",
    status: "active",
    featured: false,
    popular: true,
  },
  {
    id: "delete-pages",
    title: "Delete Pages",
    description: "Remove unwanted pages from a PDF document.",
    category: "PDF",
    relatedToolIds: ["pdf-to-word","excel-to-pdf","split-pdf","unlock-pdf"],
    keywords: ["delete", "remove", "pages", "extract", "cut", "pdf", "discard"],
    href: "/delete-pages",
    icon: Scissors,
    color: "text-red-500",
    status: "active",
    featured: false,
    popular: true,
  },
  {
    id: "organize-pdf",
    title: "Organize PDF",
    description: "Sort, delete, and rotate PDF pages in a visually interactive workspace.",
    category: "PDF",
    relatedToolIds: ["merge-pdf","excel-to-pdf","protect-pdf","unlock-pdf"],
    keywords: ["organize", "sort", "reorder", "delete", "rotate", "pdf", "arrange"],
    href: "/organize-pdf",
    icon: Layers,
    color: "text-blue-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "watermark-pdf",
    title: "Watermark PDF",
    description: "Add text or image watermarks to your PDF document.",
    category: "PDF",
    relatedToolIds: ["image-to-pdf","delete-pages","pdf-to-image","protect-pdf"],
    keywords: ["watermark", "stamp", "brand", "text", "image", "pdf", "overlay"],
    href: "/watermark-pdf",
    icon: Type,
    color: "text-indigo-500",
    status: "active",
    featured: false,
    popular: true,
  },
  {
    id: "image-to-pdf",
    title: "Image to PDF",
    description: "Convert images to PDF documents.",
    category: "PDF",
    relatedToolIds: ["pdf-to-image","watermark-pdf","merge-pdf","organize-pdf"],
    keywords: ["jpg to pdf", "convert", "image to pdf", "png to pdf", "document"],
    href: "/image-to-pdf",
    icon: FileImage,
    color: "text-rose-500",
    status: "active",
    featured: false,
    popular: false,
  },
  {
    id: "pdf-to-image",
    title: "PDF to Image",
    description: "Extract images from PDF documents.",
    category: "PDF",
    relatedToolIds: ["image-to-pdf","rotate-pdf","pdf-to-ppt","protect-pdf"],
    keywords: ["pdf to jpg", "convert", "pdf to image", "pdf to png", "extract", "document"],
    href: "/pdf-to-image",
    icon: FileText,
    color: "text-red-600",
    status: "active",
    featured: false,
    popular: false,
  },
  {
    id: "word-to-pdf",
    title: "Word to PDF",
    description: "Convert DOC and DOCX files to PDF online for free.",
    category: "PDF",
    relatedToolIds: ["organize-pdf","delete-pages","split-pdf","pdf-to-excel"],
    keywords: ["word to pdf", "docx to pdf", "convert word to pdf", "doc to pdf", "online word converter", "convert word", "doc", "docx"],
    href: "/word-to-pdf",
    icon: FileText,
    color: "text-blue-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "pdf-to-word",
    title: "PDF to Word",
    description: "Convert PDF files into editable Word documents online for free.",
    category: "PDF",
    relatedToolIds: ["excel-to-pdf","pdf-to-ppt","pdf-to-image","unlock-pdf"],
    keywords: ["pdf to word", "pdf to docx", "convert pdf to word", "online pdf converter", "pdf to editable word", "free pdf to docx"],
    href: "/pdf-to-word",
    icon: FileText,
    color: "text-blue-500",
    status: "active",
    featured: true,
    popular: true,
  },


  // VIDEO TOOLS
  {
    id: "compress-video",
    title: "Compress Video",
    description: "Reduce video file size without quality loss.",
    category: "Video",
    relatedToolIds: ["trim-video","merge-video","convert-video","mov-to-mp4"],
    keywords: ["compress", "video", "reduce", "size", "mp4", "optimize"],
    href: "/compress-video",
    icon: FileVideo,
    color: "text-blue-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "convert-video",
    title: "Convert Video",
    description: "Convert videos between popular formats.",
    category: "Video",
    relatedToolIds: ["merge-video","rotate-video","mp4-to-mp3","mov-to-mp4"],
    keywords: ["convert", "video", "mp4", "avi", "mov", "format"],
    href: "/convert-video",
    icon: Video,
    color: "text-blue-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "trim-video",
    title: "Trim Video",
    description: "Cut out unwanted parts of your video.",
    category: "Video",
    relatedToolIds: ["rotate-video","mp4-to-mp3","convert-video","merge-video"],
    keywords: ["trim", "video", "cut", "crop", "shorten"],
    href: "/trim-video",
    icon: Scissors,
    color: "text-blue-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "merge-video",
    title: "Merge Video",
    description: "Combine multiple videos into one.",
    category: "Video",
    relatedToolIds: ["mp4-to-mp3","trim-video","convert-video","rotate-video"],
    keywords: ["merge", "video", "combine", "join"],
    href: "/merge-video",
    icon: Layers,
    color: "text-blue-500",
    status: "active",
    featured: false,
    popular: true,
  },
  {
    id: "rotate-video",
    title: "Rotate Video",
    description: "Rotate or flip your video instantly.",
    category: "Video",
    relatedToolIds: ["compress-video","mov-to-mp4","merge-video","trim-video"],
    keywords: ["rotate", "video", "flip", "turn", "angle"],
    href: "/rotate-video",
    icon: RefreshCw,
    color: "text-blue-500",
    status: "active",
    featured: false,
    popular: false,
  },
  // Sub-tools for Video Conversions
  {
    id: "mp4-to-gif",
    title: "MP4 to GIF",
    description: "Convert MP4 videos to GIF animations.",
    category: "Video",
    relatedToolIds: ["mp4-to-mp3","compress-video","rotate-video","webm-to-mp4"],
    keywords: ["mp4 to gif", "convert", "video"],
    href: "/mp4-to-gif",
    icon: FileVideo,
    color: "text-blue-500",
    status: "active",
    featured: false,
    popular: true,
    isSubTool: true,
  },
  {
    id: "mp4-to-mp3",
    title: "MP4 to MP3",
    description: "Extract audio from MP4 videos.",
    category: "Video",
    relatedToolIds: ["trim-video","rotate-video","mov-to-mp4","convert-video"],
    keywords: ["mp4 to mp3", "extract", "audio"],
    href: "/mp4-to-mp3",
    icon: FileVideo,
    color: "text-blue-500",
    status: "active",
    featured: false,
    popular: true,
    isSubTool: true,
  },
  {
    id: "webm-to-mp4",
    title: "WEBM to MP4",
    description: "Convert WEBM videos to MP4 format.",
    category: "Video",
    relatedToolIds: ["convert-video","trim-video","compress-video","mp4-to-gif"],
    keywords: ["webm to mp4", "convert", "video"],
    href: "/webm-to-mp4",
    icon: FileVideo,
    color: "text-blue-500",
    status: "active",
    featured: false,
    popular: true,
    isSubTool: true,
  },
  {
    id: "mov-to-mp4",
    title: "MOV to MP4",
    description: "Convert MOV videos to MP4 format.",
    category: "Video",
    relatedToolIds: ["compress-video","mp4-to-mp3","trim-video","mp4-to-gif"],
    keywords: ["mov to mp4", "convert", "video"],
    href: "/mov-to-mp4",
    icon: FileVideo,
    color: "text-blue-500",
    status: "active",
    featured: false,
    popular: true,
    isSubTool: true,
  },

  // AUDIO TOOLS
  {
    id: "compress-audio",
    title: "Compress Audio",
    description: "Reduce audio file size easily without losing quality.",
    category: "Audio",
    relatedToolIds: ["extract-audio","flac-to-mp3","convert-audio","ogg-to-mp3"],
    keywords: ["compress", "audio", "reduce", "size", "mp3", "optimize", "m4a"],
    href: "/compress-audio",
    icon: Music,
    color: "text-emerald-400",
    status: "active",
    featured: false,
    popular: true,
  },
  {
    id: "convert-audio",
    title: "Convert Audio",
    description: "Convert audio between MP3, WAV, FLAC and more without losing quality.",
    category: "Audio",
    relatedToolIds: ["mp3-to-wav","wav-to-mp3","extract-audio","ogg-to-mp3"],
    keywords: ["convert", "audio", "mp3", "wav", "flac", "aac", "ogg"],
    href: "/convert-audio",
    icon: Music,
    color: "text-emerald-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "trim-audio",
    title: "Trim Audio",
    description: "Trim and cut audio files easily.",
    category: "Audio",
    relatedToolIds: ["mp3-to-wav","compress-audio","flac-to-mp3","merge-audio"],
    keywords: ["cut", "audio", "trim", "shorten", "ringtone"],
    href: "/trim-audio",
    icon: Scissors,
    color: "text-slate-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "merge-audio",
    title: "Merge Audio",
    description: "Combine multiple audio files into one.",
    category: "Audio",
    keywords: ["merge", "audio", "combine", "join"],
    href: "/merge-audio",
    icon: Layers,
    color: "text-slate-500",
    status: "active",
    featured: false,
    popular: false,
    relatedToolIds: ["trim-audio", "compress-audio", "convert-audio", "extract-audio"],
  },
  {
    id: "extract-audio",
    title: "Extract Audio",
    description: "Extract audio tracks from video files.",
    category: "Audio",
    keywords: ["extract", "audio", "video to audio", "mp4 to mp3"],
    href: "/extract-audio",
    icon: Music,
    color: "text-slate-500",
    status: "active",
    featured: false,
    popular: false,
    relatedToolIds: ["merge-audio", "trim-audio", "convert-audio"],
  },
  // Sub-tools for Audio Conversions
  {
    id: "mp3-to-wav",
    title: "MP3 to WAV",
    description: "Convert MP3 audio to WAV format.",
    category: "Audio",
    relatedToolIds: ["ogg-to-mp3","flac-to-mp3","wav-to-mp3","compress-audio"],
    keywords: ["mp3 to wav", "convert", "audio"],
    href: "/mp3-to-wav",
    icon: Music,
    color: "text-emerald-500",
    status: "active",
    featured: false,
    popular: true,
    isSubTool: true,
  },
  {
    id: "wav-to-mp3",
    title: "WAV to MP3",
    description: "Convert WAV audio to MP3 format.",
    category: "Audio",
    relatedToolIds: ["ogg-to-mp3","merge-audio","mp3-to-wav","trim-audio"],
    keywords: ["wav to mp3", "convert", "audio"],
    href: "/wav-to-mp3",
    icon: Music,
    color: "text-emerald-500",
    status: "active",
    featured: false,
    popular: true,
    isSubTool: true,
  },
  {
    id: "flac-to-mp3",
    title: "FLAC to MP3",
    description: "Convert FLAC audio to MP3 format.",
    category: "Audio",
    relatedToolIds: ["wav-to-mp3","merge-audio","trim-audio","extract-audio"],
    keywords: ["flac to mp3", "convert", "audio"],
    href: "/flac-to-mp3",
    icon: Music,
    color: "text-emerald-500",
    status: "active",
    featured: false,
    popular: true,
    isSubTool: true,
  },
  {
    id: "ogg-to-mp3",
    title: "OGG to MP3",
    description: "Convert OGG audio to MP3 format.",
    category: "Audio",
    relatedToolIds: ["merge-audio","extract-audio","wav-to-mp3","flac-to-mp3"],
    keywords: ["ogg to mp3", "convert", "audio"],
    href: "/ogg-to-mp3",
    icon: Music,
    color: "text-emerald-500",
    status: "active",
    featured: false,
    popular: true,
    isSubTool: true,
  },

  // AI TOOLS
  {
    id: "background-remover",
    title: "Background Remover",
    description: "Remove background from images instantly with AI.",
    category: "AI",
    keywords: ["background", "remove", "ai", "transparent", "png"],
    href: "/remove-background",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: true,
    popular: true,
    relatedToolIds: ["compress-image", "resize-image"],
  },
  {
    id: "image-upscaler",
    title: "Image Upscaler",
    description: "Upscale images up to 4x without losing quality.",
    category: "AI",
    relatedToolIds: ["object-remover","ai-image-enhancer"],
    keywords: ["upscale", "image", "ai", "enlarge", "quality"],
    href: "/image-upscaler",
    icon: Image,
    color: "text-blue-500",
    status: "active",
    featured: false,
    popular: true,
  },
  {
    id: "object-remover",
    title: "Object Remover",
    description: "Remove unwanted objects from photos.",
    category: "AI",
    relatedToolIds: ["image-upscaler","ai-image-enhancer"],
    keywords: ["object", "remove", "ai", "erase", "clean"],
    href: "/object-remover",
    icon: Wand2,
    color: "text-purple-600",
    status: "active",
    featured: false,
    popular: true,
  },
  {
    id: "ai-image-enhancer",
    title: "AI Image Enhancer",
    description: "Enhance colors and details automatically.",
    category: "AI",
    relatedToolIds: ["object-remover","image-upscaler"],
    keywords: ["enhance", "image", "ai", "color", "details"],
    href: "/ai-image-enhancer",
    icon: Sparkles,
    color: "text-purple-500",
    status: "active",
    featured: false,
    popular: false,
  },

  // UTILITIES
  {
    id: "qr-generator",
    title: "QR Code Generator",
    description: "Create customizable QR codes instantly.",
    category: "Utilities",
    relatedToolIds: ["json-formatter","barcode-generator","color-picker"],
    keywords: ["qr", "code", "generator", "create", "link"],
    href: "/qr-generator",
    icon: QrCode,
    color: "text-blue-500",
    status: "active",
    featured: true,
    popular: true,
  },

  {
    id: "color-picker",
    title: "Color Picker",
    description: "Extract colors from images or generate palettes.",
    category: "Utilities",
    relatedToolIds: ["barcode-generator","qr-generator","json-formatter"],
    keywords: ["color", "picker", "palette", "hex", "rgb"],
    href: "/color-picker",
    icon: Palette,
    color: "text-pink-500",
    status: "active",
    featured: false,
    popular: true,
  },
  {
    id: "json-formatter",
    title: "JSON Formatter",
    description: "Format, validate, and minify JSON data.",
    category: "Utilities",
    relatedToolIds: ["barcode-generator","qr-generator","color-picker"],
    keywords: ["json", "format", "validate", "minify", "code"],
    href: "/json-formatter",
    icon: Code,
    color: "text-emerald-500",
    status: "active",
    featured: false,
    popular: false,
  },
  {
    id: "barcode-generator",
    title: "Barcode Generator",
    description: "Generate Code128, EAN, UPC, and other barcodes instantly.",
    category: "Utilities",
    relatedToolIds: ["qr-generator","json-formatter","color-picker"],
    keywords: ["barcode", "generate", "code128", "ean", "upc", "create", "png", "svg", "pdf"],
    href: "/barcode-generator",
    icon: Barcode,
    color: "text-sky-500",
    status: "active",
    featured: false,
    popular: false,
  }
];
