import { 
  ImageDown, Maximize, Crop, RotateCw, FileDown, 
  FileText, Layers, Scissors, FileImage, 
  Video, Music, Wand2, QrCode, Sparkles, Image, FileVideo, Barcode, Palette, Code,
  LucideIcon, Unlock, Lock, Type, RefreshCw
} from "lucide-react";

export interface ToolDefinition {
  id: string;
  title: string;
  description: string;
  category: "Image" | "PDF" | "Video" | "Audio" | "AI" | "Utilities";
  keywords: string[];
  href: string;
  icon: LucideIcon;
  color: string;
  status: "active" | "coming-soon";
  featured: boolean;
  popular: boolean;
  relatedToolIds?: string[];
  isSubTool?: boolean;
}

export const TOOLS: ToolDefinition[] = [
  // IMAGE TOOLS
  {
    id: "background-remover",
    title: "Background Remover",
    description: "Remove background from images instantly with AI.",
    category: "Image",
    keywords: ["background", "remove", "ai", "transparent", "png"],
    href: "/tools/ai/background-remover",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: true,
    popular: true,
    relatedToolIds: ["compress-image", "resize-image"],
  },
  // Sub-tools for Image Conversions
  {
    id: "jpg-to-png",
    title: "JPG to PNG",
    description: "Convert JPG images to PNG format with transparency.",
    category: "Image",
    keywords: ["jpg to png", "convert", "image"],
    href: "/tools/image/jpg-to-png",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: true,
    isSubTool: true,
    relatedToolIds: ["convert-image", "png-to-jpg"],
  },
  {
    id: "png-to-jpg",
    title: "PNG to JPG",
    description: "Convert PNG images to JPG format.",
    category: "Image",
    keywords: ["png to jpg", "convert", "image"],
    href: "/tools/image/png-to-jpg",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: true,
    isSubTool: true,
    relatedToolIds: ["convert-image", "jpg-to-png"],
  },
  {
    id: "webp-to-png",
    title: "WEBP to PNG",
    description: "Convert WEBP images to PNG format.",
    category: "Image",
    keywords: ["webp to png", "convert", "image"],
    href: "/tools/image/webp-to-png",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: false,
    isSubTool: true,
    relatedToolIds: ["convert-image"],
  },
  {
    id: "png-to-webp",
    title: "PNG to WEBP",
    description: "Convert PNG images to WEBP format.",
    category: "Image",
    keywords: ["png to webp", "convert", "image"],
    href: "/tools/image/png-to-webp",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: false,
    isSubTool: true,
    relatedToolIds: ["convert-image"],
  },
  {
    id: "jpg-to-webp",
    title: "JPG to WEBP",
    description: "Convert JPG images to WEBP format.",
    category: "Image",
    keywords: ["jpg to webp", "convert", "image"],
    href: "/tools/image/jpg-to-webp",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: false,
    isSubTool: true,
    relatedToolIds: ["convert-image"],
  },
  {
    id: "webp-to-jpg",
    title: "WEBP to JPG",
    description: "Convert WEBP images to JPG format.",
    category: "Image",
    keywords: ["webp to jpg", "convert", "image"],
    href: "/tools/image/webp-to-jpg",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: false,
    isSubTool: true,
    relatedToolIds: ["convert-image"],
  },
  {
    id: "avif-to-jpg",
    title: "AVIF to JPG",
    description: "Convert AVIF images to JPG format.",
    category: "Image",
    keywords: ["avif to jpg", "convert", "image"],
    href: "/tools/image/avif-to-jpg",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: false,
    isSubTool: true,
    relatedToolIds: ["convert-image"],
  },
  {
    id: "jpg-to-avif",
    title: "JPG to AVIF",
    description: "Convert JPG images to AVIF format.",
    category: "Image",
    keywords: ["jpg to avif", "convert", "image"],
    href: "/tools/image/jpg-to-avif",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: false,
    isSubTool: true,
    relatedToolIds: ["convert-image"],
  },
  {
    id: "bmp-to-png",
    title: "BMP to PNG",
    description: "Convert BMP images to PNG format.",
    category: "Image",
    keywords: ["bmp to png", "convert", "image"],
    href: "/tools/image/bmp-to-png",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: false,
    isSubTool: true,
    relatedToolIds: ["convert-image"],
  },
  {
    id: "gif-to-png",
    title: "GIF to PNG",
    description: "Convert GIF images to PNG format.",
    category: "Image",
    keywords: ["gif to png", "convert", "image"],
    href: "/tools/image/gif-to-png",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: false,
    isSubTool: true,
    relatedToolIds: ["convert-image"],
  },
  {
    id: "compress-image",
    title: "Compress Image",
    description: "Reduce image size without losing quality.",
    category: "Image",
    keywords: ["compress", "image", "reduce", "size", "tiny", "jpg", "png", "webp", "optimize"],
    href: "/tools/image/compress",
    icon: ImageDown,
    color: "text-green-600",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "resize-image",
    title: "Resize Image",
    description: "Change image dimensions instantly.",
    category: "Image",
    keywords: ["resize", "image", "dimensions", "scale", "width", "height", "pixel", "resolution"],
    href: "/tools/image/resize",
    icon: Maximize,
    color: "text-blue-600",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "crop-image",
    title: "Crop Image",
    description: "Crop photos to exact ratios or custom sizes.",
    category: "Image",
    keywords: ["crop", "image", "cut", "trim", "ratio", "square", "aspect"],
    href: "/tools/image/crop",
    icon: Crop,
    color: "text-purple-600",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "rotate-image",
    title: "Rotate Image",
    description: "Rotate or flip images easily.",
    category: "Image",
    keywords: ["rotate", "image", "flip", "turn", "degree", "angle", "upside down"],
    href: "/tools/image/rotate",
    icon: RotateCw,
    color: "text-amber-600",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "convert-image",
    title: "Convert Image",
    description: "Convert between JPG, PNG, WEBP and AVIF.",
    category: "Image",
    keywords: ["convert", "image", "format", "change", "jpg", "png", "webp", "avif", "gif"],
    href: "/tools/image/convert",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: true,
    popular: true,
  },

  // PDF TOOLS
  {
    id: "compress-pdf",
    title: "Compress PDF",
    description: "Reduce PDF file size for easy sharing.",
    category: "PDF",
    keywords: ["compress", "pdf", "reduce", "size", "document", "optimize"],
    href: "/tools/pdf/compress",
    icon: FileText,
    color: "text-red-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "merge-pdf",
    title: "Merge PDF",
    description: "Combine multiple PDFs into one.",
    category: "PDF",
    keywords: ["merge", "pdf", "combine", "join", "together", "document"],
    href: "/tools/pdf/merge",
    icon: Layers,
    color: "text-orange-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "split-pdf",
    title: "Split PDF",
    description: "Extract specific pages from a PDF.",
    category: "PDF",
    keywords: ["split", "pdf", "extract", "separate", "pages", "divide"],
    href: "/tools/pdf/split",
    icon: Scissors,
    color: "text-amber-500",
    status: "active",
    featured: false,
    popular: true,
  },
  {
    id: "unlock-pdf",
    title: "Unlock PDF",
    description: "Remove password protection from PDF.",
    category: "PDF",
    keywords: ["unlock", "pdf", "password", "decrypt", "remove", "protection", "security"],
    href: "/tools/pdf/unlock",
    icon: Unlock,
    color: "text-green-500",
    status: "active",
    featured: false,
    popular: true,
  },
  {
    id: "protect-pdf",
    title: "Protect PDF",
    description: "Encrypt your PDF files with a password.",
    category: "PDF",
    keywords: ["protect", "pdf", "password", "encrypt", "secure", "permissions", "lock"],
    href: "/tools/pdf/protect-pdf",
    icon: Lock,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: true,
  },
  {
    id: "rotate-pdf",
    title: "Rotate PDF",
    description: "Rotate PDF pages easily and permanently.",
    category: "PDF",
    keywords: ["rotate", "pdf", "turn", "pages", "degree", "orientation"],
    href: "/tools/pdf/rotate-pdf",
    icon: RotateCw,
    color: "text-amber-500",
    status: "active",
    featured: false,
    popular: true,
  },
  {
    id: "delete-pages",
    title: "Delete Pages",
    description: "Remove unwanted pages from a PDF document.",
    category: "PDF",
    keywords: ["delete", "remove", "pages", "extract", "cut", "pdf", "discard"],
    href: "/tools/pdf/delete-pages",
    icon: Scissors,
    color: "text-red-500",
    status: "active",
    featured: false,
    popular: true,
  },
  {
    id: "organize-pdf",
    title: "Organize PDF",
    description: "Sort, delete, and rotate PDF pages in a visually interactive workspace.",
    category: "PDF",
    keywords: ["organize", "sort", "reorder", "delete", "rotate", "pdf", "arrange"],
    href: "/tools/pdf/organize-pdf",
    icon: Layers,
    color: "text-blue-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "watermark-pdf",
    title: "Watermark PDF",
    description: "Add text or image watermarks to your PDF document.",
    category: "PDF",
    keywords: ["watermark", "stamp", "brand", "text", "image", "pdf", "overlay"],
    href: "/tools/pdf/watermark-pdf",
    icon: Type,
    color: "text-indigo-500",
    status: "active",
    featured: false,
    popular: true,
  },
  {
    id: "image-to-pdf",
    title: "Image to PDF",
    description: "Convert images to PDF documents.",
    category: "PDF",
    keywords: ["jpg to pdf", "convert", "image to pdf", "png to pdf", "document"],
    href: "/tools/pdf/image-to-pdf",
    icon: FileImage,
    color: "text-rose-500",
    status: "active",
    featured: false,
    popular: false,
  },
  {
    id: "pdf-to-image",
    title: "PDF to Image",
    description: "Extract images from PDF documents.",
    category: "PDF",
    keywords: ["pdf to jpg", "convert", "pdf to image", "pdf to png", "extract", "document"],
    href: "/tools/pdf/pdf-to-image",
    icon: FileText,
    color: "text-red-600",
    status: "active",
    featured: false,
    popular: false,
  },
  {
    id: "word-to-pdf",
    title: "Word to PDF",
    description: "Convert DOC and DOCX files to PDF online for free.",
    category: "PDF",
    keywords: ["word to pdf", "docx to pdf", "convert word to pdf", "doc to pdf", "online word converter", "convert word", "doc", "docx"],
    href: "/tools/pdf/word-to-pdf",
    icon: FileText,
    color: "text-blue-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "pdf-to-word",
    title: "PDF to Word",
    description: "Convert PDF files into editable Word documents online for free.",
    category: "PDF",
    keywords: ["pdf to word", "pdf to docx", "convert pdf to word", "online pdf converter", "pdf to editable word", "free pdf to docx"],
    href: "/tools/pdf/pdf-to-word",
    icon: FileText,
    color: "text-blue-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "excel-to-pdf",
    title: "Excel to PDF",
    description: "Convert Excel spreadsheets to PDF while preserving formatting.",
    category: "PDF",
    keywords: ["excel", "spreadsheet", "pdf", "convert", "xlsx", "xls", "table"],
    href: "/tools/pdf/excel-to-pdf",
    icon: FileText,
    color: "text-green-600",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "pdf-to-excel",
    title: "PDF to Excel",
    description: "Extract tables and structured data from PDFs into editable Excel spreadsheets.",
    category: "PDF",
    keywords: ["pdf to excel", "extract table", "pdf to xlsx", "convert pdf to excel"],
    href: "/tools/pdf/pdf-to-excel",
    icon: FileText,
    color: "text-green-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "ppt-to-pdf",
    title: "PPT to PDF",
    description: "Convert PowerPoint presentations to high-quality PDF documents.",
    category: "PDF",
    keywords: ["powerpoint", "ppt", "pptx", "convert", "pdf"],
    href: "/tools/pdf/ppt-to-pdf",
    icon: FileText,
    color: "text-orange-600",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "pdf-to-ppt",
    title: "PDF to PowerPoint",
    description: "Convert PDF documents into editable PowerPoint presentations.",
    category: "PDF",
    keywords: ["powerpoint", "pdf", "pdf to ppt", "pdf to pptx", "convert"],
    href: "/tools/pdf/pdf-to-ppt",
    icon: FileText,
    color: "text-orange-500",
    status: "active",
    featured: true,
    popular: true,
  },

  // VIDEO TOOLS
  {
    id: "compress-video",
    title: "Compress Video",
    description: "Reduce video file size without quality loss.",
    category: "Video",
    keywords: ["compress", "video", "reduce", "size", "mp4", "optimize"],
    href: "/tools/video/compress-video",
    icon: FileVideo,
    color: "text-blue-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "convert-video",
    title: "Convert Video",
    description: "Convert videos between popular formats.",
    category: "Video",
    keywords: ["convert", "video", "mp4", "avi", "mov", "format"],
    href: "/tools/video/convert-video",
    icon: Video,
    color: "text-blue-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "trim-video",
    title: "Trim Video",
    description: "Cut out unwanted parts of your video.",
    category: "Video",
    keywords: ["trim", "video", "cut", "crop", "shorten"],
    href: "/tools/video/trim-video",
    icon: Scissors,
    color: "text-blue-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "merge-video",
    title: "Merge Video",
    description: "Combine multiple videos into one.",
    category: "Video",
    keywords: ["merge", "video", "combine", "join"],
    href: "/tools/video/merge-video",
    icon: Layers,
    color: "text-blue-500",
    status: "active",
    featured: false,
    popular: true,
  },
  {
    id: "rotate-video",
    title: "Rotate Video",
    description: "Rotate or flip your video instantly.",
    category: "Video",
    keywords: ["rotate", "video", "flip", "turn", "angle"],
    href: "/tools/video/rotate-video",
    icon: RefreshCw,
    color: "text-blue-500",
    status: "active",
    featured: false,
    popular: false,
  },
  // Sub-tools for Video Conversions
  {
    id: "mp4-to-gif",
    title: "MP4 to GIF",
    description: "Convert MP4 videos to GIF animations.",
    category: "Video",
    keywords: ["mp4 to gif", "convert", "video"],
    href: "/tools/video/mp4-to-gif",
    icon: FileVideo,
    color: "text-blue-500",
    status: "active",
    featured: false,
    popular: true,
    isSubTool: true,
  },
  {
    id: "mp4-to-mp3",
    title: "MP4 to MP3",
    description: "Extract audio from MP4 videos.",
    category: "Video",
    keywords: ["mp4 to mp3", "extract", "audio"],
    href: "/tools/video/mp4-to-mp3",
    icon: FileVideo,
    color: "text-blue-500",
    status: "active",
    featured: false,
    popular: true,
    isSubTool: true,
  },
  {
    id: "webm-to-mp4",
    title: "WEBM to MP4",
    description: "Convert WEBM videos to MP4 format.",
    category: "Video",
    keywords: ["webm to mp4", "convert", "video"],
    href: "/tools/video/webm-to-mp4",
    icon: FileVideo,
    color: "text-blue-500",
    status: "active",
    featured: false,
    popular: true,
    isSubTool: true,
  },
  {
    id: "mov-to-mp4",
    title: "MOV to MP4",
    description: "Convert MOV videos to MP4 format.",
    category: "Video",
    keywords: ["mov to mp4", "convert", "video"],
    href: "/tools/video/mov-to-mp4",
    icon: FileVideo,
    color: "text-blue-500",
    status: "active",
    featured: false,
    popular: true,
    isSubTool: true,
  },

  // AUDIO TOOLS
  {
    id: "compress-audio",
    title: "Compress Audio",
    description: "Reduce audio file size easily without losing quality.",
    category: "Audio",
    keywords: ["compress", "audio", "reduce", "size", "mp3", "optimize", "m4a"],
    href: "/tools/audio/compress-audio",
    icon: Music,
    color: "text-emerald-400",
    status: "active",
    featured: false,
    popular: true,
  },
  {
    id: "convert-audio",
    title: "Convert Audio",
    description: "Convert audio between MP3, WAV, FLAC and more without losing quality.",
    category: "Audio",
    keywords: ["convert", "audio", "mp3", "wav", "flac", "aac", "ogg"],
    href: "/tools/audio/convert-audio",
    icon: Music,
    color: "text-emerald-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "trim-audio",
    title: "Trim Audio",
    description: "Trim and cut audio files easily.",
    category: "Audio",
    keywords: ["cut", "audio", "trim", "shorten", "ringtone"],
    href: "/tools/audio/trim-audio",
    icon: Scissors,
    color: "text-slate-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "merge-audio",
    title: "Merge Audio",
    description: "Combine multiple audio files into one.",
    category: "Audio",
    keywords: ["merge", "audio", "combine", "join"],
    href: "/tools/audio/merge-audio",
    icon: Layers,
    color: "text-slate-500",
    status: "active",
    featured: false,
    popular: false,
    relatedToolIds: ["trim-audio", "compress-audio", "convert-audio", "extract-audio"],
  },
  {
    id: "extract-audio",
    title: "Extract Audio",
    description: "Extract audio tracks from video files.",
    category: "Audio",
    keywords: ["extract", "audio", "video to audio", "mp4 to mp3"],
    href: "/tools/audio/extract-audio",
    icon: Music,
    color: "text-slate-500",
    status: "active",
    featured: false,
    popular: false,
    relatedToolIds: ["merge-audio", "trim-audio", "convert-audio"],
  },
  // Sub-tools for Audio Conversions
  {
    id: "mp3-to-wav",
    title: "MP3 to WAV",
    description: "Convert MP3 audio to WAV format.",
    category: "Audio",
    keywords: ["mp3 to wav", "convert", "audio"],
    href: "/tools/audio/mp3-to-wav",
    icon: Music,
    color: "text-emerald-500",
    status: "active",
    featured: false,
    popular: true,
    isSubTool: true,
  },
  {
    id: "wav-to-mp3",
    title: "WAV to MP3",
    description: "Convert WAV audio to MP3 format.",
    category: "Audio",
    keywords: ["wav to mp3", "convert", "audio"],
    href: "/tools/audio/wav-to-mp3",
    icon: Music,
    color: "text-emerald-500",
    status: "active",
    featured: false,
    popular: true,
    isSubTool: true,
  },
  {
    id: "flac-to-mp3",
    title: "FLAC to MP3",
    description: "Convert FLAC audio to MP3 format.",
    category: "Audio",
    keywords: ["flac to mp3", "convert", "audio"],
    href: "/tools/audio/flac-to-mp3",
    icon: Music,
    color: "text-emerald-500",
    status: "active",
    featured: false,
    popular: true,
    isSubTool: true,
  },
  {
    id: "ogg-to-mp3",
    title: "OGG to MP3",
    description: "Convert OGG audio to MP3 format.",
    category: "Audio",
    keywords: ["ogg to mp3", "convert", "audio"],
    href: "/tools/audio/ogg-to-mp3",
    icon: Music,
    color: "text-emerald-500",
    status: "active",
    featured: false,
    popular: true,
    isSubTool: true,
  },

  // AI TOOLS

  {
    id: "image-upscaler",
    title: "Image Upscaler",
    description: "Upscale images up to 4x without losing quality.",
    category: "AI",
    keywords: ["upscale", "image", "ai", "enlarge", "quality"],
    href: "/tools/ai/upscaler",
    icon: Image,
    color: "text-slate-400",
    status: "coming-soon",
    featured: false,
    popular: false,
  },
  {
    id: "object-remover",
    title: "Object Remover",
    description: "Remove unwanted objects from photos.",
    category: "AI",
    keywords: ["object", "remove", "ai", "erase", "clean"],
    href: "/tools/ai/object-remover",
    icon: Wand2,
    color: "text-slate-400",
    status: "coming-soon",
    featured: false,
    popular: false,
  },
  {
    id: "ai-image-enhancer",
    title: "AI Image Enhancer",
    description: "Enhance colors and details automatically.",
    category: "AI",
    keywords: ["enhance", "image", "ai", "color", "details"],
    href: "/tools/ai/enhancer",
    icon: Sparkles,
    color: "text-slate-400",
    status: "coming-soon",
    featured: false,
    popular: false,
  },

  // UTILITIES
  {
    id: "qr-generator",
    title: "QR Code Generator",
    description: "Create customizable QR codes instantly.",
    category: "Utilities",
    keywords: ["qr", "code", "generator", "create", "link"],
    href: "/tools/utilities/qr",
    icon: QrCode,
    color: "text-slate-400",
    status: "coming-soon",
    featured: true,
    popular: false,
  },
  {
    id: "barcode-generator",
    title: "Barcode Generator",
    description: "Generate standard barcodes for products.",
    category: "Utilities",
    keywords: ["barcode", "generator", "create", "product"],
    href: "/tools/utilities/barcode",
    icon: Barcode,
    color: "text-slate-400",
    status: "coming-soon",
    featured: false,
    popular: false,
  },
  {
    id: "color-picker",
    title: "Color Picker",
    description: "Extract colors from images or generate palettes.",
    category: "Utilities",
    keywords: ["color", "picker", "palette", "hex", "rgb"],
    href: "/tools/utilities/color-picker",
    icon: Palette,
    color: "text-slate-400",
    status: "coming-soon",
    featured: false,
    popular: false,
  },
  {
    id: "json-formatter",
    title: "JSON Formatter",
    description: "Format, validate, and minify JSON data.",
    category: "Utilities",
    keywords: ["json", "format", "validate", "minify", "code"],
    href: "/tools/utilities/json",
    icon: Code,
    color: "text-slate-400",
    status: "coming-soon",
    featured: false,
    popular: false,
  }
];
