import { 
  ImageDown, Maximize, Crop, RotateCw, FileDown, 
  FileText, Layers, Scissors, FileImage, 
  Video, Music, Wand2, QrCode, Sparkles, Image, Wrench, FileVideo, Mic, Barcode, Palette, Code,
  LucideIcon, Unlock, Lock
} from "lucide-react";

export interface ToolDefinition {
  id: string;
  title: string;
  description: string;
  category: "Image" | "PDF" | "Video" | "Audio" | "AI" | "Utilities";
  keywords: string[];
  href: string;
  icon: LucideIcon;
  color: string;
  status: "active" | "coming-soon";
  featured: boolean;
  popular: boolean;
}

export const TOOLS: ToolDefinition[] = [
  // IMAGE TOOLS
  {
    id: "compress-image",
    title: "Compress Image",
    description: "Reduce image size without losing quality.",
    category: "Image",
    keywords: ["compress", "image", "reduce", "size", "tiny", "jpg", "png", "webp", "optimize"],
    href: "/tools/image/compress",
    icon: ImageDown,
    color: "text-green-600",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "resize-image",
    title: "Resize Image",
    description: "Change image dimensions instantly.",
    category: "Image",
    keywords: ["resize", "image", "dimensions", "scale", "width", "height", "pixel", "resolution"],
    href: "/tools/image/resize",
    icon: Maximize,
    color: "text-blue-600",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "crop-image",
    title: "Crop Image",
    description: "Crop photos to exact ratios or custom sizes.",
    category: "Image",
    keywords: ["crop", "image", "cut", "trim", "ratio", "square", "aspect"],
    href: "/tools/image/crop",
    icon: Crop,
    color: "text-purple-600",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "rotate-image",
    title: "Rotate Image",
    description: "Rotate or flip images easily.",
    category: "Image",
    keywords: ["rotate", "image", "flip", "turn", "degree", "angle", "upside down"],
    href: "/tools/image/rotate",
    icon: RotateCw,
    color: "text-amber-600",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "convert-image",
    title: "Convert Image",
    description: "Convert between JPG, PNG, WEBP and AVIF.",
    category: "Image",
    keywords: ["convert", "image", "format", "change", "jpg", "png", "webp", "avif", "gif"],
    href: "/tools/image/convert",
    icon: FileDown,
    color: "text-indigo-600",
    status: "active",
    featured: true,
    popular: true,
  },

  // PDF TOOLS
  {
    id: "compress-pdf",
    title: "Compress PDF",
    description: "Reduce PDF file size for easy sharing.",
    category: "PDF",
    keywords: ["compress", "pdf", "reduce", "size", "document", "optimize"],
    href: "/tools/pdf/compress",
    icon: FileText,
    color: "text-red-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "merge-pdf",
    title: "Merge PDF",
    description: "Combine multiple PDFs into one.",
    category: "PDF",
    keywords: ["merge", "pdf", "combine", "join", "together", "document"],
    href: "/tools/pdf/merge",
    icon: Layers,
    color: "text-orange-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "split-pdf",
    title: "Split PDF",
    description: "Extract specific pages from a PDF.",
    category: "PDF",
    keywords: ["split", "pdf", "extract", "separate", "pages", "divide"],
    href: "/tools/pdf/split",
    icon: Scissors,
    color: "text-amber-500",
    status: "active",
    featured: false,
    popular: true,
  },
  {
    id: "unlock-pdf",
    title: "Unlock PDF",
    description: "Remove password protection from PDF.",
    category: "PDF",
    keywords: ["unlock", "pdf", "password", "decrypt", "remove", "protection", "security"],
    href: "/tools/pdf/unlock",
    icon: Unlock,
    color: "text-green-500",
    status: "active",
    featured: false,
    popular: true,
  },
  {
    id: "protect-pdf",
    title: "Protect PDF",
    description: "Encrypt your PDF files with a password.",
    category: "PDF",
    keywords: ["protect", "pdf", "password", "encrypt", "secure", "permissions", "lock"],
    href: "/tools/pdf/protect-pdf",
    icon: Lock,
    color: "text-indigo-600",
    status: "active",
    featured: false,
    popular: true,
  },
  {
    id: "image-to-pdf",
    title: "Image to PDF",
    description: "Convert images to PDF documents.",
    category: "PDF",
    keywords: ["jpg to pdf", "convert", "image to pdf", "png to pdf", "document"],
    href: "/tools/pdf/image-to-pdf",
    icon: FileImage,
    color: "text-rose-500",
    status: "active",
    featured: false,
    popular: false,
  },
  {
    id: "pdf-to-image",
    title: "PDF to Image",
    description: "Extract images from PDF documents.",
    category: "PDF",
    keywords: ["pdf to jpg", "convert", "pdf to image", "pdf to png", "extract", "document"],
    href: "/tools/pdf/pdf-to-image",
    icon: FileText,
    color: "text-red-600",
    status: "active",
    featured: false,
    popular: false,
  },
  {
    id: "word-to-pdf",
    title: "Word to PDF",
    description: "Convert DOC and DOCX files to PDF online for free.",
    category: "PDF",
    keywords: ["word to pdf", "docx to pdf", "convert word to pdf", "doc to pdf", "online word converter", "convert word", "doc", "docx"],
    href: "/tools/pdf/word-to-pdf",
    icon: FileText,
    color: "text-blue-500",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "pdf-to-word",
    title: "PDF to Word",
    description: "Convert PDF files into editable Word documents online for free.",
    category: "PDF",
    keywords: ["pdf to word", "pdf to docx", "convert pdf to word", "online pdf converter", "pdf to editable word", "free pdf to docx"],
    href: "/tools/pdf/pdf-to-word",
    icon: FileText,
    color: "text-blue-600",
    status: "active",
    featured: true,
    popular: true,
  },
  {
    id: "excel-to-pdf",
    title: "Excel to PDF",
    description: "Convert Excel spreadsheets to PDF format.",
    category: "PDF",
    keywords: ["excel", "xls", "xlsx", "convert", "pdf"],
    href: "#",
    icon: FileText,
    color: "text-slate-400",
    status: "coming-soon",
    featured: false,
    popular: false,
  },
  {
    id: "ppt-to-pdf",
    title: "PPT to PDF",
    description: "Convert PowerPoint presentations to PDF.",
    category: "PDF",
    keywords: ["ppt", "pptx", "powerpoint", "convert", "pdf"],
    href: "#",
    icon: FileText,
    color: "text-slate-400",
    status: "coming-soon",
    featured: false,
    popular: false,
  },

  // VIDEO TOOLS
  {
    id: "compress-video",
    title: "Compress Video",
    description: "Reduce video file size without quality loss.",
    category: "Video",
    keywords: ["compress", "video", "reduce", "size", "mp4", "optimize"],
    href: "/tools/video/compress",
    icon: FileVideo,
    color: "text-slate-400",
    status: "coming-soon",
    featured: true,
    popular: false,
  },
  {
    id: "convert-video",
    title: "Convert Video",
    description: "Convert videos between popular formats.",
    category: "Video",
    keywords: ["convert", "video", "mp4", "avi", "mov", "format"],
    href: "/tools/video/convert",
    icon: Video,
    color: "text-slate-400",
    status: "coming-soon",
    featured: false,
    popular: false,
  },
  {
    id: "trim-video",
    title: "Trim Video",
    description: "Cut out unwanted parts of your video.",
    category: "Video",
    keywords: ["trim", "video", "cut", "crop", "shorten"],
    href: "/tools/video/trim",
    icon: Scissors,
    color: "text-slate-400",
    status: "coming-soon",
    featured: false,
    popular: false,
  },
  {
    id: "merge-video",
    title: "Merge Video",
    description: "Combine multiple videos into one.",
    category: "Video",
    keywords: ["merge", "video", "combine", "join"],
    href: "#",
    icon: Layers,
    color: "text-slate-400",
    status: "coming-soon",
    featured: false,
    popular: false,
  },
  {
    id: "rotate-video",
    title: "Rotate Video",
    description: "Rotate or flip videos easily.",
    category: "Video",
    keywords: ["rotate", "video", "flip", "turn"],
    href: "#",
    icon: RotateCw,
    color: "text-slate-400",
    status: "coming-soon",
    featured: false,
    popular: false,
  },

  // AUDIO TOOLS
  {
    id: "compress-audio",
    title: "Compress Audio",
    description: "Reduce audio file size easily.",
    category: "Audio",
    keywords: ["compress", "audio", "reduce", "size", "mp3", "optimize"],
    href: "/tools/audio/compress",
    icon: Music,
    color: "text-slate-400",
    status: "coming-soon",
    featured: false,
    popular: false,
  },
  {
    id: "audio-converter",
    title: "Convert Audio",
    description: "Convert audio between MP3, WAV, FLAC and more.",
    category: "Audio",
    keywords: ["convert", "audio", "mp3", "wav", "flac"],
    href: "/tools/audio/convert",
    icon: Music,
    color: "text-slate-400",
    status: "coming-soon",
    featured: false,
    popular: false,
  },
  {
    id: "audio-cutter",
    title: "Audio Cutter",
    description: "Trim and cut audio files easily.",
    category: "Audio",
    keywords: ["cut", "audio", "trim", "shorten", "ringtone"],
    href: "/tools/audio/cut",
    icon: Scissors,
    color: "text-slate-400",
    status: "coming-soon",
    featured: false,
    popular: false,
  },
  {
    id: "merge-audio",
    title: "Merge Audio",
    description: "Combine multiple audio files into one.",
    category: "Audio",
    keywords: ["merge", "audio", "combine", "join"],
    href: "/tools/audio/merge",
    icon: Layers,
    color: "text-slate-400",
    status: "coming-soon",
    featured: false,
    popular: false,
  },

  // AI TOOLS
  {
    id: "background-remover",
    title: "Background Remover",
    description: "Remove background from images instantly with AI.",
    category: "AI",
    keywords: ["background", "remove", "ai", "transparent", "png"],
    href: "/tools/ai/background-remover",
    icon: Sparkles,
    color: "text-slate-400",
    status: "coming-soon",
    featured: true,
    popular: false,
  },
  {
    id: "image-upscaler",
    title: "Image Upscaler",
    description: "Upscale images up to 4x without losing quality.",
    category: "AI",
    keywords: ["upscale", "image", "ai", "enlarge", "quality"],
    href: "/tools/ai/upscaler",
    icon: Image,
    color: "text-slate-400",
    status: "coming-soon",
    featured: false,
    popular: false,
  },
  {
    id: "object-remover",
    title: "Object Remover",
    description: "Remove unwanted objects from photos.",
    category: "AI",
    keywords: ["object", "remove", "ai", "erase", "clean"],
    href: "/tools/ai/object-remover",
    icon: Wand2,
    color: "text-slate-400",
    status: "coming-soon",
    featured: false,
    popular: false,
  },
  {
    id: "ai-image-enhancer",
    title: "AI Image Enhancer",
    description: "Enhance colors and details automatically.",
    category: "AI",
    keywords: ["enhance", "image", "ai", "color", "details"],
    href: "/tools/ai/enhancer",
    icon: Sparkles,
    color: "text-slate-400",
    status: "coming-soon",
    featured: false,
    popular: false,
  },

  // UTILITIES
  {
    id: "qr-generator",
    title: "QR Code Generator",
    description: "Create customizable QR codes instantly.",
    category: "Utilities",
    keywords: ["qr", "code", "generator", "create", "link"],
    href: "/tools/utilities/qr",
    icon: QrCode,
    color: "text-slate-400",
    status: "coming-soon",
    featured: true,
    popular: false,
  },
  {
    id: "barcode-generator",
    title: "Barcode Generator",
    description: "Generate standard barcodes for products.",
    category: "Utilities",
    keywords: ["barcode", "generator", "create", "product"],
    href: "/tools/utilities/barcode",
    icon: Barcode,
    color: "text-slate-400",
    status: "coming-soon",
    featured: false,
    popular: false,
  },
  {
    id: "color-picker",
    title: "Color Picker",
    description: "Extract colors from images or generate palettes.",
    category: "Utilities",
    keywords: ["color", "picker", "palette", "hex", "rgb"],
    href: "/tools/utilities/color-picker",
    icon: Palette,
    color: "text-slate-400",
    status: "coming-soon",
    featured: false,
    popular: false,
  },
  {
    id: "json-formatter",
    title: "JSON Formatter",
    description: "Format, validate, and minify JSON data.",
    category: "Utilities",
    keywords: ["json", "format", "validate", "minify", "code"],
    href: "/tools/utilities/json",
    icon: Code,
    color: "text-slate-400",
    status: "coming-soon",
    featured: false,
    popular: false,
  }
];
