"use client";

import React from "react";
import { ToolLayout } from "@/components/tool/ToolLayout";
import { ToolHeader } from "@/components/tool/ToolHeader";
import { FAQSection } from "@/components/tool/FAQSection";
import { AboutTool } from "@/components/tool/AboutTool";
import { RelatedTools } from "@/components/tool/RelatedTools";
import { BarcodeTool } from "@/components/tool/barcode/BarcodeTool";
import { ScanBarcode } from "lucide-react";
import Head from "next/head";

export default function BarcodeGeneratorPage() {
  const faqs = [
    {
      question: "Which barcode formats are supported?",
      answer: "We support all major industry standards including Code128, Code39, EAN-13, EAN-8, UPC-A, UPC-E, ITF (Interleaved 2 of 5), MSI, Pharmacode, and Codabar."
    },
    {
      question: "Are these barcodes valid for retail products?",
      answer: "Yes, formats like UPC-A and EAN-13 generated by this tool strictly adhere to GS1 specifications and are scannable by standard retail POS systems. However, you must officially register and purchase your UPC/EAN prefixes from GS1 if you are selling commercial products."
    },
    {
      question: "Which download format should I choose?",
      answer: "For digital use and websites, SVG (Scalable Vector Graphics) is best because it never loses quality. For printing or sharing, use PDF. For standard image usage, use PNG."
    },
    {
      question: "Is my data safe?",
      answer: "Absolutely. This tool runs entirely in your browser using JavaScript. Your barcode data is never sent to our servers or stored anywhere."
    }
  ];

  const structuredData = {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    "name": "Fileinator Barcode Generator",
    "applicationCategory": "UtilitiesApplication",
    "operatingSystem": "Any",
    "offers": {
      "@type": "Offer",
      "price": "0",
      "priceCurrency": "USD"
    },
    "description": "Generate professional barcodes instantly. Supports Code128, Code39, EAN-13, UPC, and more. Export as vector SVG, PNG, or PDF."
  };

  return (
    <>
      <Head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
        />
      </Head>
      <ToolLayout>
        
        <ToolHeader 
          title="Free Barcode Generator"
          subtitle="Generate high-quality, professional barcodes instantly. Supports Code128, EAN, UPC, and more."
          icon={<ScanBarcode className="w-6 h-6" />}
        />

        <div className="mt-8 mb-16">
          <BarcodeTool />
        </div>

        <RelatedTools />
        
        <FAQSection faqs={faqs} />
        
        <AboutTool 
          title="About the Barcode Generator"
          content={
            <>
              <p>
                The Fileinator Barcode Generator is a professional-grade, privacy-first tool designed to instantly encode your text and numeric data into industry-standard barcode formats. Whether you're managing inventory, building an asset tracking system, or creating retail product labels, this tool provides you with the flexibility you need.
              </p>
              <p>
                <strong>Supported Formats:</strong>
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-2 mb-4">
                <li><strong>Code 128 & Code 39:</strong> High-density alphanumeric formats widely used in logistics, warehousing, and asset tracking.</li>
                <li><strong>EAN-13, EAN-8, UPC-A, UPC-E:</strong> The global standards for retail products and Point-of-Sale (POS) systems.</li>
                <li><strong>ITF (Interleaved 2 of 5):</strong> Commonly used on corrugated boxes and packaging materials.</li>
                <li><strong>Codabar, MSI, Pharmacode:</strong> Specialized formats used in blood banks, libraries, and pharmaceuticals.</li>
              </ul>
              <p>
                We prioritize your privacy and data security. Unlike many other online barcode generators that process your data on remote servers, the Fileinator Barcode Generator executes all encoding logic securely within your own web browser. Your data never leaves your device.
              </p>
            </>
          }
        />

      </ToolLayout>
    </>
  );
}
